import * as vscode from 'vscode';
import * as fs from 'fs';
import { parseFLR, FlrData, PATH_NODE_TYPE_NAMES, PATH_GRAPH_TYPE_NAMES } from './flrParser';

class FLRDocument implements vscode.CustomDocument {
    constructor(public readonly uri: vscode.Uri, public readonly data: FlrData) {}
    dispose() {}
}

export class FLRViewerProvider implements vscode.CustomReadonlyEditorProvider<FLRDocument> {
    private static readonly viewType = 'flrViewer.flrFile';

    public static register(context: vscode.ExtensionContext): vscode.Disposable {
        return vscode.window.registerCustomEditorProvider(
            FLRViewerProvider.viewType,
            new FLRViewerProvider(context),
            { webviewOptions: { retainContextWhenHidden: true } }
        );
    }

    constructor(private readonly context: vscode.ExtensionContext) {}

    async openCustomDocument(uri: vscode.Uri): Promise<FLRDocument> {
        const raw = await fs.promises.readFile(uri.fsPath);
        const data = parseFLR(Buffer.from(raw));
        return new FLRDocument(uri, data);
    }

    async resolveCustomEditor(
        document: FLRDocument,
        webviewPanel: vscode.WebviewPanel
    ): Promise<void> {
        webviewPanel.webview.options = { enableScripts: true };

        // Serialize parsed data to JSON for the webview
        const flr = document.data;
        const jsonData = JSON.stringify({
            version: flr.version,
            vertices: flr.vertices,
            triangles: flr.triangles,
            pathGraph: flr.pathGraph,
            bounds: flr.bounds,
            fileName: document.uri.fsPath.split('/').pop() || 'unknown.flr',
        });

        webviewPanel.webview.html = this._getHtml(jsonData);
    }

    private _getHtml(jsonData: string): string {
        // Escape JSON for safe embedding in HTML
        const escaped = jsonData.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');

        const lines: string[] = [
            '<!DOCTYPE html>',
            '<html lang="en">',
            '<head>',
            '<meta charset="UTF-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
            '<title>FLR Viewer</title>',
            '<style>',
            '  * { margin: 0; padding: 0; box-sizing: border-box; }',
            '  body { overflow: hidden; background: #1e1e1e; font-family: var(--vscode-font-family, monospace); color: #ccc; }',
            '  #canvas { display: block; cursor: grab; }',
            '  #canvas.dragging { cursor: grabbing; }',
            '  #info-panel {',
            '    position: absolute; top: 8px; left: 8px;',
            '    background: rgba(30,30,30,0.92); border: 1px solid #444; border-radius: 4px;',
            '    padding: 8px 12px; font-size: 12px; line-height: 1.5; pointer-events: none;',
            '    max-width: 400px;',
            '  }',
            '  #info-panel .label { color: #888; }',
            '  #info-panel .value { color: #ddd; }',
            '  #info-panel .title { color: #4ec9b0; font-weight: bold; font-size: 13px; margin-bottom: 2px; }',
            '  #status-bar {',
            '    position: absolute; bottom: 0; left: 0; right: 0;',
            '    background: rgba(30,30,30,0.92); border-top: 1px solid #444;',
            '    padding: 4px 12px; font-size: 11px; display: flex; gap: 16px;',
            '    pointer-events: none;',
            '  }',
            '  #status-bar .section { white-space: nowrap; }',
            '  #legend {',
            '    position: absolute; top: 8px; right: 8px;',
            '    background: rgba(30,30,30,0.92); border: 1px solid #444; border-radius: 4px;',
            '    padding: 8px 12px; font-size: 11px; line-height: 1.6; pointer-events: none;',
            '  }',
            '  #legend .swatch { display: inline-block; width: 12px; height: 3px; margin-right: 6px; vertical-align: middle; }',
            '  #help-hint {',
            '    position: absolute; bottom: 28px; right: 8px;',
            '    background: rgba(30,30,30,0.85); border: 1px solid #444; border-radius: 4px;',
            '    padding: 6px 10px; font-size: 11px; line-height: 1.5; pointer-events: none;',
            '    color: #888;',
            '  }',
            '</style>',
            '</head>',
            '<body>',
            '<canvas id="canvas"></canvas>',
            '<div id="info-panel"></div>',
            '<div id="status-bar"></div>',
            '<div id="legend"></div>',
            '<div id="help-hint">',
            '  <span style="color:#aaa">F</span> Fit &nbsp; <span style="color:#aaa">G</span> Grid &nbsp; <span style="color:#aaa">P</span> Path graph &nbsp; <span style="color:#aaa">E</span> Edge mode',
            '</div>',
            '<script>',
            '(function() {',
            '',
            'var flr = JSON.parse(\'' + escaped + '\');',
            '',
            '// ---- Canvas setup ----',
            'var canvas = document.getElementById("canvas");',
            'var ctx = canvas.getContext("2d");',
            '',
            '// ---- View state ----',
            'var zoom = 1;',
            'var viewX = 0, viewZ = 0;',
            'var isDragging = false;',
            'var lastMouseX = 0, lastMouseY = 0;',
            'var mouseWorldX = 0, mouseWorldZ = 0;',
            'var showGrid = true;',
            'var showPathGraph = true;',
            'var edgeMode = 0; // 0=all, 1=walls only, 2=portals only',
            'var edgeModeNames = ["All edges", "Walls only", "Portals only"];',
            'var hoveredTriIdx = -1;',
            'var hoveredNodeIdx = -1;',
            '',
            '// ---- Edge colors ----',
            'var EDGE_COLORS = {',
            '  0: "#FF4444",   // uncrossable (wall)',
            '  1: "#44FF88",   // connected (walkable)',
            '  2: "#FFAA44",   // blocking',
            '};',
            'var PORTAL_COLOR = "#4488FF";',
            '',
            '// ---- Path node colors by type ----',
            'var NODE_COLORS = {',
            '  0: "#4488FF",   // CellPortal',
            '  1: "#FFFFFF",   // CellWaypoint',
            '  2: "#FFCC44",   // CellPOI',
            '  3: "#44FF88",   // BuildingEntrance',
            '  4: "#888888",   // BuildingCell',
            '  5: "#44DDDD",   // BuildingPortal',
            '  6: "#6688FF",   // CityBuildingEntrance',
            '  7: "#AAAAAA",   // CityWaypoint',
            '  8: "#FFAA44",   // CityPOI',
            '  9: "#666666",   // CityBuilding',
            '  10: "#88FF88",  // CityEntrance',
            '  11: "#AA88CC",  // BuildingCellPart',
            '  12: "#FF4444",  // Invalid',
            '};',
            '',
            'var PATH_NODE_NAMES = ' + JSON.stringify(PATH_NODE_TYPE_NAMES) + ';',
            'var PATH_GRAPH_NAMES = ' + JSON.stringify(PATH_GRAPH_TYPE_NAMES) + ';',
            '',
            '// ---- Coordinate conversion ----',
            'function worldToScreenX(wx) { return canvas.width / 2 + (wx - viewX) * zoom; }',
            'function worldToScreenY(wz) { return canvas.height / 2 - (wz - viewZ) * zoom; }',
            'function screenToWorldX(sx) { return viewX + (sx - canvas.width / 2) / zoom; }',
            'function screenToWorldZ(sy) { return viewZ - (sy - canvas.height / 2) / zoom; }',
            '',
            '// ---- Resize ----',
            'function resize() {',
            '  canvas.width = window.innerWidth;',
            '  canvas.height = window.innerHeight;',
            '  render();',
            '}',
            'window.addEventListener("resize", resize);',
            '',
            '// ---- Fit to bounds ----',
            'function fitView() {',
            '  var b = flr.bounds;',
            '  viewX = (b.minX + b.maxX) / 2;',
            '  viewZ = (b.minZ + b.maxZ) / 2;',
            '  var rangeX = (b.maxX - b.minX) || 20;',
            '  var rangeZ = (b.maxZ - b.minZ) || 20;',
            '  var pad = 1.15;',
            '  zoom = Math.min(canvas.width / (rangeX * pad), canvas.height / (rangeZ * pad));',
            '  if (zoom <= 0 || !isFinite(zoom)) { zoom = 10; }',
            '  render();',
            '}',
            '',
            '// ---- Grid ----',
            'function drawGrid() {',
            '  if (!showGrid) { return; }',
            '  var left = screenToWorldX(0);',
            '  var right = screenToWorldX(canvas.width);',
            '  var top = screenToWorldZ(0);',
            '  var bottom = screenToWorldZ(canvas.height);',
            '',
            '  // Choose grid spacing based on zoom',
            '  var pixelsPerUnit = zoom;',
            '  var gridSpacing = 1;',
            '  if (pixelsPerUnit < 4) { gridSpacing = 10; }',
            '  else if (pixelsPerUnit < 20) { gridSpacing = 5; }',
            '  else if (pixelsPerUnit < 50) { gridSpacing = 2; }',
            '',
            '  ctx.strokeStyle = "rgba(255,255,255,0.06)";',
            '  ctx.lineWidth = 1;',
            '  ctx.beginPath();',
            '',
            '  var startX = Math.floor(left / gridSpacing) * gridSpacing;',
            '  for (var gx = startX; gx <= right; gx += gridSpacing) {',
            '    var sx = worldToScreenX(gx);',
            '    ctx.moveTo(sx, 0);',
            '    ctx.lineTo(sx, canvas.height);',
            '  }',
            '',
            '  var minZ = Math.min(top, bottom);',
            '  var maxZ = Math.max(top, bottom);',
            '  var startZ = Math.floor(minZ / gridSpacing) * gridSpacing;',
            '  for (var gz = startZ; gz <= maxZ; gz += gridSpacing) {',
            '    var sy = worldToScreenY(gz);',
            '    ctx.moveTo(0, sy);',
            '    ctx.lineTo(canvas.width, sy);',
            '  }',
            '  ctx.stroke();',
            '',
            '  // Origin axes',
            '  ctx.strokeStyle = "rgba(255,255,255,0.15)";',
            '  ctx.lineWidth = 1;',
            '  ctx.beginPath();',
            '  var ox = worldToScreenX(0);',
            '  var oz = worldToScreenY(0);',
            '  ctx.moveTo(ox, 0); ctx.lineTo(ox, canvas.height);',
            '  ctx.moveTo(0, oz); ctx.lineTo(canvas.width, oz);',
            '  ctx.stroke();',
            '}',
            '',
            '// ---- Triangle rendering ----',
            'function drawTriangles() {',
            '  var verts = flr.vertices;',
            '  var tris = flr.triangles;',
            '',
            '  // Pass 1: fills',
            '  for (var i = 0; i < tris.length; i++) {',
            '    var t = tris[i];',
            '    var v0 = verts[t.corner1];',
            '    var v1 = verts[t.corner2];',
            '    var v2 = verts[t.corner3];',
            '    if (!v0 || !v1 || !v2) { continue; }',
            '',
            '    ctx.beginPath();',
            '    ctx.moveTo(worldToScreenX(v0.x), worldToScreenY(v0.z));',
            '    ctx.lineTo(worldToScreenX(v1.x), worldToScreenY(v1.z));',
            '    ctx.lineTo(worldToScreenX(v2.x), worldToScreenY(v2.z));',
            '    ctx.closePath();',
            '',
            '    if (i === hoveredTriIdx) {',
            '      ctx.fillStyle = "rgba(255,255,255,0.15)";',
            '    } else if (t.fallthrough) {',
            '      ctx.fillStyle = "rgba(255,100,100,0.08)";',
            '    } else {',
            '      ctx.fillStyle = "rgba(80,180,120,0.10)";',
            '    }',
            '    ctx.fill();',
            '  }',
            '',
            '  // Pass 2: edges',
            '  ctx.lineWidth = 1;',
            '  for (var i = 0; i < tris.length; i++) {',
            '    var t = tris[i];',
            '    var v0 = verts[t.corner1];',
            '    var v1 = verts[t.corner2];',
            '    var v2 = verts[t.corner3];',
            '    if (!v0 || !v1 || !v2) { continue; }',
            '',
            '    drawEdge(v0, v1, t.edgeType1, t.portalId1);',
            '    drawEdge(v1, v2, t.edgeType2, t.portalId2);',
            '    drawEdge(v2, v0, t.edgeType3, t.portalId3);',
            '  }',
            '}',
            '',
            'function drawEdge(va, vb, edgeType, portalId) {',
            '  var isPortal = portalId !== -1 && portalId !== 0xFFFFFFFF;',
            '',
            '  // Edge mode filtering',
            '  if (edgeMode === 1 && edgeType !== 0 && !isPortal) { return; }',
            '  if (edgeMode === 2 && !isPortal) { return; }',
            '',
            '  if (isPortal) {',
            '    ctx.strokeStyle = PORTAL_COLOR;',
            '    ctx.lineWidth = 2;',
            '  } else {',
            '    ctx.strokeStyle = EDGE_COLORS[edgeType] || "#666";',
            '    ctx.lineWidth = edgeType === 0 ? 1.5 : 0.7;',
            '  }',
            '',
            '  ctx.beginPath();',
            '  ctx.moveTo(worldToScreenX(va.x), worldToScreenY(va.z));',
            '  ctx.lineTo(worldToScreenX(vb.x), worldToScreenY(vb.z));',
            '  ctx.stroke();',
            '}',
            '',
            '// ---- Path graph rendering ----',
            'function drawPathGraph() {',
            '  if (!showPathGraph || !flr.pathGraph) { return; }',
            '  var pg = flr.pathGraph;',
            '',
            '  // Draw edges as dashed lines',
            '  ctx.save();',
            '  ctx.setLineDash([4, 4]);',
            '  ctx.strokeStyle = "rgba(200,200,200,0.3)";',
            '  ctx.lineWidth = 1;',
            '  for (var i = 0; i < pg.edges.length; i++) {',
            '    var e = pg.edges[i];',
            '    var fromNode = pg.nodes[e.from];',
            '    var toNode = pg.nodes[e.to];',
            '    if (!fromNode || !toNode) { continue; }',
            '    ctx.beginPath();',
            '    ctx.moveTo(worldToScreenX(fromNode.x), worldToScreenY(fromNode.z));',
            '    ctx.lineTo(worldToScreenX(toNode.x), worldToScreenY(toNode.z));',
            '    ctx.stroke();',
            '  }',
            '  ctx.restore();',
            '',
            '  // Draw nodes as circles',
            '  for (var i = 0; i < pg.nodes.length; i++) {',
            '    var n = pg.nodes[i];',
            '    var sx = worldToScreenX(n.x);',
            '    var sy = worldToScreenY(n.z);',
            '    var r = Math.max(4, n.radius * zoom);',
            '    r = Math.min(r, 20);',
            '',
            '    var color = NODE_COLORS[n.type] || "#888";',
            '',
            '    ctx.beginPath();',
            '    ctx.arc(sx, sy, r, 0, Math.PI * 2);',
            '    if (i === hoveredNodeIdx) {',
            '      ctx.fillStyle = color;',
            '      ctx.fill();',
            '      ctx.strokeStyle = "#fff";',
            '      ctx.lineWidth = 2;',
            '      ctx.stroke();',
            '    } else {',
            '      ctx.fillStyle = color + "88";',
            '      ctx.fill();',
            '      ctx.strokeStyle = color;',
            '      ctx.lineWidth = 1;',
            '      ctx.stroke();',
            '    }',
            '',
            '    // Label at sufficient zoom',
            '    if (zoom > 8 || i === hoveredNodeIdx) {',
            '      ctx.fillStyle = "#fff";',
            '      ctx.font = "10px monospace";',
            '      ctx.textAlign = "center";',
            '      ctx.fillText(PATH_NODE_NAMES[n.type] || ("Type " + n.type), sx, sy - r - 4);',
            '    }',
            '  }',
            '}',
            '',
            '// ---- Hit testing ----',
            'function pointInTriangle(px, pz, v0, v1, v2) {',
            '  var d1 = (px - v1.x) * (v0.z - v1.z) - (v0.x - v1.x) * (pz - v1.z);',
            '  var d2 = (px - v2.x) * (v1.z - v2.z) - (v1.x - v2.x) * (pz - v2.z);',
            '  var d3 = (px - v0.x) * (v2.z - v0.z) - (v2.x - v0.x) * (pz - v0.z);',
            '  var hasNeg = (d1 < 0) || (d2 < 0) || (d3 < 0);',
            '  var hasPos = (d1 > 0) || (d2 > 0) || (d3 > 0);',
            '  return !(hasNeg && hasPos);',
            '}',
            '',
            'function findHoveredTriangle(wx, wz) {',
            '  var verts = flr.vertices;',
            '  var tris = flr.triangles;',
            '  for (var i = 0; i < tris.length; i++) {',
            '    var t = tris[i];',
            '    var v0 = verts[t.corner1];',
            '    var v1 = verts[t.corner2];',
            '    var v2 = verts[t.corner3];',
            '    if (!v0 || !v1 || !v2) { continue; }',
            '    if (pointInTriangle(wx, wz, v0, v1, v2)) { return i; }',
            '  }',
            '  return -1;',
            '}',
            '',
            'function findHoveredNode(wx, wz) {',
            '  if (!flr.pathGraph) { return -1; }',
            '  var nodes = flr.pathGraph.nodes;',
            '  var bestDist = Infinity;',
            '  var bestIdx = -1;',
            '  var threshold = 10 / zoom; // 10 pixels in world coords',
            '  for (var i = 0; i < nodes.length; i++) {',
            '    var n = nodes[i];',
            '    var dx = n.x - wx;',
            '    var dz = n.z - wz;',
            '    var d = Math.sqrt(dx * dx + dz * dz);',
            '    if (d < threshold && d < bestDist) {',
            '      bestDist = d;',
            '      bestIdx = i;',
            '    }',
            '  }',
            '  return bestIdx;',
            '}',
            '',
            '// ---- Info panel ----',
            'function updateInfoPanel() {',
            '  var el = document.getElementById("info-panel");',
            '  var pg = flr.pathGraph;',
            '  var graphInfo = pg ? " &middot; Graph: " + (PATH_GRAPH_NAMES[pg.graphType] || "?") + " (" + pg.nodes.length + " nodes)" : "";',
            '  el.innerHTML = [',
            '    "<div class=\\"title\\">" + flr.fileName + "</div>",',
            '    "<span class=\\"label\\">Version:</span> <span class=\\"value\\">" + flr.version + "</span>",',
            '    " &middot; <span class=\\"label\\">Verts:</span> <span class=\\"value\\">" + flr.vertices.length + "</span>",',
            '    " &middot; <span class=\\"label\\">Tris:</span> <span class=\\"value\\">" + flr.triangles.length + "</span>",',
            '    graphInfo,',
            '  ].join("");',
            '}',
            '',
            '// ---- Status bar ----',
            'function updateStatusBar() {',
            '  var parts = [];',
            '  parts.push("<span class=\\"section\\">X: " + mouseWorldX.toFixed(2) + " Z: " + mouseWorldZ.toFixed(2) + "</span>");',
            '  parts.push("<span class=\\"section\\">Zoom: " + zoom.toFixed(2) + "x</span>");',
            '',
            '  if (hoveredNodeIdx >= 0 && flr.pathGraph) {',
            '    var n = flr.pathGraph.nodes[hoveredNodeIdx];',
            '    parts.push("<span class=\\"section\\" style=\\"color:#4ec9b0\\">Node #" + n.id + " " + (PATH_NODE_NAMES[n.type] || "Type " + n.type) + " (" + n.x.toFixed(2) + ", " + n.z.toFixed(2) + ", y=" + n.y.toFixed(2) + ") r=" + n.radius.toFixed(1) + "</span>");',
            '  } else if (hoveredTriIdx >= 0) {',
            '    var t = flr.triangles[hoveredTriIdx];',
            '    var edges = "e[" + t.edgeType1 + "," + t.edgeType2 + "," + t.edgeType3 + "]";',
            '    var portals = "";',
            '    if (t.portalId1 !== -1 || t.portalId2 !== -1 || t.portalId3 !== -1) {',
            '      portals = " portals[" + t.portalId1 + "," + t.portalId2 + "," + t.portalId3 + "]";',
            '    }',
            '    var ft = t.fallthrough ? " FALLTHROUGH" : "";',
            '    parts.push("<span class=\\"section\\" style=\\"color:#ddd\\">Tri #" + t.index + " " + edges + portals + ft + "</span>");',
            '  }',
            '',
            '  parts.push("<span class=\\"section\\" style=\\"color:#888\\">" + edgeModeNames[edgeMode] + "</span>");',
            '',
            '  document.getElementById("status-bar").innerHTML = parts.join("");',
            '}',
            '',
            '// ---- Legend ----',
            'function updateLegend() {',
            '  var items = [',
            '    { color: "#44FF88", label: "Walkable" },',
            '    { color: "#FF4444", label: "Wall" },',
            '    { color: "#FFAA44", label: "Blocking" },',
            '    { color: "#4488FF", label: "Portal" },',
            '  ];',
            '  if (flr.pathGraph && showPathGraph) {',
            '    items.push({ color: "", label: "---" });',
            '    var seen = {};',
            '    for (var i = 0; i < flr.pathGraph.nodes.length; i++) {',
            '      var nt = flr.pathGraph.nodes[i].type;',
            '      if (!seen[nt]) {',
            '        seen[nt] = true;',
            '        items.push({ color: NODE_COLORS[nt] || "#888", label: PATH_NODE_NAMES[nt] || ("Type " + nt) });',
            '      }',
            '    }',
            '  }',
            '  var html = items.map(function(item) {',
            '    if (item.label === "---") { return "<div style=\\"border-top:1px solid #444;margin:3px 0\\"></div>"; }',
            '    return "<div><span class=\\"swatch\\" style=\\"background:" + item.color + "\\"></span>" + item.label + "</div>";',
            '  }).join("");',
            '  document.getElementById("legend").innerHTML = html;',
            '}',
            '',
            '// ---- Main render ----',
            'function render() {',
            '  ctx.clearRect(0, 0, canvas.width, canvas.height);',
            '  drawGrid();',
            '  drawTriangles();',
            '  drawPathGraph();',
            '  updateStatusBar();',
            '}',
            '',
            '// ---- Mouse events ----',
            'canvas.addEventListener("mousedown", function(e) {',
            '  if (e.button === 0) {',
            '    isDragging = true;',
            '    lastMouseX = e.clientX;',
            '    lastMouseY = e.clientY;',
            '    canvas.classList.add("dragging");',
            '  }',
            '});',
            '',
            'canvas.addEventListener("mousemove", function(e) {',
            '  var rect = canvas.getBoundingClientRect();',
            '  var mx = e.clientX - rect.left;',
            '  var my = e.clientY - rect.top;',
            '  mouseWorldX = screenToWorldX(mx);',
            '  mouseWorldZ = screenToWorldZ(my);',
            '',
            '  if (isDragging) {',
            '    var dx = e.clientX - lastMouseX;',
            '    var dy = e.clientY - lastMouseY;',
            '    viewX -= dx / zoom;',
            '    viewZ += dy / zoom;',
            '    lastMouseX = e.clientX;',
            '    lastMouseY = e.clientY;',
            '    render();',
            '    return;',
            '  }',
            '',
            '  // Hit test',
            '  var prevTri = hoveredTriIdx;',
            '  var prevNode = hoveredNodeIdx;',
            '  hoveredNodeIdx = showPathGraph ? findHoveredNode(mouseWorldX, mouseWorldZ) : -1;',
            '  hoveredTriIdx = hoveredNodeIdx < 0 ? findHoveredTriangle(mouseWorldX, mouseWorldZ) : -1;',
            '',
            '  if (hoveredTriIdx !== prevTri || hoveredNodeIdx !== prevNode) {',
            '    render();',
            '  } else {',
            '    updateStatusBar();',
            '  }',
            '});',
            '',
            'canvas.addEventListener("mouseup", function() {',
            '  isDragging = false;',
            '  canvas.classList.remove("dragging");',
            '});',
            '',
            'canvas.addEventListener("mouseleave", function() {',
            '  isDragging = false;',
            '  canvas.classList.remove("dragging");',
            '});',
            '',
            '// Zoom toward cursor',
            'canvas.addEventListener("wheel", function(e) {',
            '  e.preventDefault();',
            '  var rect = canvas.getBoundingClientRect();',
            '  var mx = e.clientX - rect.left;',
            '  var my = e.clientY - rect.top;',
            '',
            '  var wxBefore = screenToWorldX(mx);',
            '  var wzBefore = screenToWorldZ(my);',
            '',
            '  var factor = e.deltaY > 0 ? 0.9 : 1.1;',
            '  zoom *= factor;',
            '  zoom = Math.max(0.01, Math.min(1000, zoom));',
            '',
            '  // Adjust view so world point under cursor stays fixed',
            '  var wxAfter = screenToWorldX(mx);',
            '  var wzAfter = screenToWorldZ(my);',
            '  viewX -= (wxAfter - wxBefore);',
            '  viewZ -= (wzAfter - wzBefore);',
            '',
            '  render();',
            '}, { passive: false });',
            '',
            '// Right-click to center',
            'canvas.addEventListener("contextmenu", function(e) {',
            '  e.preventDefault();',
            '  var rect = canvas.getBoundingClientRect();',
            '  var mx = e.clientX - rect.left;',
            '  var my = e.clientY - rect.top;',
            '  viewX = screenToWorldX(mx);',
            '  viewZ = screenToWorldZ(my);',
            '  render();',
            '});',
            '',
            '// ---- Keyboard shortcuts ----',
            'document.addEventListener("keydown", function(e) {',
            '  var key = e.key.toLowerCase();',
            '  if (key === "f") {',
            '    fitView();',
            '  } else if (key === "g") {',
            '    showGrid = !showGrid;',
            '    render();',
            '  } else if (key === "p") {',
            '    showPathGraph = !showPathGraph;',
            '    updateLegend();',
            '    render();',
            '  } else if (key === "e") {',
            '    edgeMode = (edgeMode + 1) % 3;',
            '    render();',
            '  }',
            '});',
            '',
            '// ---- Init ----',
            'resize();',
            'updateInfoPanel();',
            'updateLegend();',
            'fitView();',
            '',
            '})();',
            '</script>',
            '</body>',
            '</html>',
        ];

        return lines.join('\n');
    }
}
