-- test_bunker Screenplay
-- Generated by Building NPC Planner
-- POB: poi_all_impl_bunker_s02.pob (11 cells)
-- Example of a small bunker with progressive difficulty

test_bunker = ScreenPlay:new {
	buildingId = 12345678, -- UPDATE THIS: Your building object ID
	zone = "tatooine", -- UPDATE THIS: Your planet zone

	spawnPoints = {
		-- Cell 1: entry (Tier 1 - Easiest)
		[1] = {
			{
				template = "stormtrooper",
				x = -8.50,
				z = 0.00,
				y = 4.20,
				heading = 90,
				cellIndex = 1,
				tier = 1,
			},
			{
				template = "stormtrooper",
				x = 8.50,
				z = 0.00,
				y = 4.20,
				heading = 270,
				cellIndex = 1,
				tier = 1,
			},
			{
				template = "stormtrooper",
				x = 0.00,
				z = 0.00,
				y = -5.00,
				heading = 180,
				cellIndex = 1,
				tier = 1,
			},
			{
				template = "stormtrooper_squad_leader",
				x = 0.00,
				z = 0.00,
				y = 0.00,
				heading = 0,
				cellIndex = 1,
				tier = 1,
			},
		},
		-- Cell 2: hall1 (Tier 2)
		[2] = {
			{
				template = "stormtrooper_squad_leader",
				x = -5.00,
				z = 0.00,
				y = 2.00,
				heading = 45,
				cellIndex = 2,
				tier = 2,
			},
			{
				template = "stormtrooper",
				x = 5.00,
				z = 0.00,
				y = 2.00,
				heading = 315,
				cellIndex = 2,
				tier = 2,
			},
		},
		-- Cell 3: hall2 (Tier 2)
		[3] = {
			{
				template = "stormtrooper_squad_leader",
				x = -5.00,
				z = 0.00,
				y = 2.00,
				heading = 45,
				cellIndex = 3,
				tier = 2,
			},
			{
				template = "stormtrooper",
				x = 5.00,
				z = 0.00,
				y = 2.00,
				heading = 315,
				cellIndex = 3,
				tier = 2,
			},
			{
				template = "stormtrooper",
				x = 0.00,
				z = 0.00,
				y = -3.00,
				heading = 180,
				cellIndex = 3,
				tier = 2,
			},
		},
		-- Cell 10: bunker (Tier 5 - Boss Room)
		[10] = {
			{
				template = "dark_trooper",
				x = 0.00,
				z = 0.00,
				y = 0.00,
				heading = 0,
				cellIndex = 10,
				tier = 5,
			},
			{
				template = "stormtrooper_commando",
				x = -6.00,
				z = 0.00,
				y = 3.00,
				heading = 90,
				cellIndex = 10,
				tier = 5,
			},
			{
				template = "stormtrooper_commando",
				x = 6.00,
				z = 0.00,
				y = 3.00,
				heading = 270,
				cellIndex = 10,
				tier = 5,
			},
			{
				template = "stormtrooper_commando",
				x = -6.00,
				z = 0.00,
				y = -3.00,
				heading = 90,
				cellIndex = 10,
				tier = 5,
			},
			{
				template = "stormtrooper_commando",
				x = 6.00,
				z = 0.00,
				y = -3.00,
				heading = 270,
				cellIndex = 10,
				tier = 5,
			},
		},
	},
}

registerScreenPlay("test_bunker", true)

function test_bunker:start()
	if (not isZoneEnabled(self.zone)) then
		return
	end

	self:spawnMobiles()
end

function test_bunker:spawnMobiles()
	local pSceneObject = getSceneObject(self.buildingId)
	if (pSceneObject == nil) then
		printLuaError("test_bunker: Building " .. self.buildingId .. " not found")
		return
	end

	for cellIndex, spawns in pairs(self.spawnPoints) do
		for i, spawn in ipairs(spawns) do
			local pCell = getCell(pSceneObject, cellIndex)
			if (pCell ~= nil) then
				local pMobile = spawnMobile(self.zone, spawn.template, 0, spawn.x, spawn.z, spawn.y, spawn.heading, pCell)
				if (pMobile ~= nil) then
					createObserver(OBJECTDESTRUCTION, "test_bunker", "notifyMobileDead", pMobile)
				else
					printLuaError("test_bunker: Failed to spawn " .. spawn.template .. " in cell " .. cellIndex)
				end
			else
				printLuaError("test_bunker: Cell " .. cellIndex .. " not found in building")
			end
		end
	end
end

function test_bunker:notifyMobileDead(pMobile, pKiller)
	if (pMobile == nil) then
		return 1
	end

	local cellId = SceneObject(pMobile):getParentID()
	local x = SceneObject(pMobile):getPositionX()
	local z = SceneObject(pMobile):getPositionZ()
	local y = SceneObject(pMobile):getPositionY()
	local heading = SceneObject(pMobile):getDirectionAngle()
	local template = SceneObject(pMobile):getObjectName()

	-- 5 minute respawn timer (300000 milliseconds = 5 minutes)
	createTimedEvent(300000, "test_bunker", "respawnMobile", pMobile, template .. ":" .. cellId .. ":" .. x .. ":" .. z .. ":" .. y .. ":" .. heading)
	return 0
end

function test_bunker:respawnMobile(pSceneObject, args)
	local parts = {}
	for part in string.gmatch(args, "[^:]+") do
		table.insert(parts, part)
	end

	if (#parts < 6) then
		printLuaError("test_bunker: Invalid respawn args: " .. args)
		return 0
	end

	local template = parts[1]
	local cellId = tonumber(parts[2])
	local x = tonumber(parts[3])
	local z = tonumber(parts[4])
	local y = tonumber(parts[5])
	local heading = tonumber(parts[6])

	local pCell = getSceneObject(cellId)
	if (pCell ~= nil) then
		local pMobile = spawnMobile(self.zone, template, 0, x, z, y, heading, pCell)
		if (pMobile ~= nil) then
			createObserver(OBJECTDESTRUCTION, "test_bunker", "notifyMobileDead", pMobile)
		end
	end
	return 0
end
